name: Continuous Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    
    - name: Install dependencies
      run: npm ci

    - name: Set up deployment key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

    - name: Deploy
      env:
        USE_SSH: true
      run: |
        git config --global user.email 'actions@github.com'
        git config --global user.name  'gh-actions'
        ./deploy