name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    # paths-ignore:
    #   - .github/**
    branches: [main]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js 15.x
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    
    - name: Install Google Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb
        rm -rf google-chrome-stable_current_amd64.deb
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: |
        # Screenshot
        google-chrome --headless --disable-gpu --enable-logging --screenshot="$(pwd)/resume.png" --window-size=1536,1000 --no-margins "$(pwd)/index.html"

        # Full PDF
        google-chrome --headless --disable-gpu --enable-logging --print-to-pdf="$(pwd)/resume.pdf" --run-all-compositor-stages-before-draw --window-size=1536,1000 --virtual-time-budget=20000 --no-margins "$(pwd)/index.html"

        # Mini PDF
        cp style.css style.css.old
        echo -e '\n.value { display: none; }' >> style.css
        google-chrome --headless --disable-gpu --enable-logging --print-to-pdf="$(pwd)/resume-mini.pdf" --run-all-compositor-stages-before-draw --window-size=1536,1000 --virtual-time-budget=20000 --no-margins "$(pwd)/index.html"
        mv style.css.old style.css

    - name: Set up deployment key
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

    - name: Deploy
      env:
        USE_SSH: true
      run: |
        git config --global user.email 'actions@github.com'
        git config --global user.name  'gh-actions'

        if [ -n "$(git status --porcelain)" ]; then
          # Create .nojekyll
          echo Ensuring .nojekyll...
          if ! [ -f .nojekyll ]; then
            touch .nojekyll
          fi

          # Delete .gitignore
          echo Deleting .gitignore...
          if [ -f .gitignore ]; then
            rm -rf .gitignore
          fi

          echo Staging files...
          git add .
          echo Committing...
          git commit --allow-empty-message --no-edit
        fi

        echo Pushing...
        git push -f origin main:gh-pages